//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChoThueOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIENBANGN
    {
        public string Số_BBGN { get; set; }
        public string Số_xe { get; set; }
        public string Mã_KH { get; set; }
        public string Mã_NV { get; set; }
        public System.DateTime Ngày_giao { get; set; }
        public int Km_đi { get; set; }
        public string Xăng_đi { get; set; }
        public string Trạng_thái_đi { get; set; }
        public System.DateTime Ngày_nhận { get; set; }
        public int Km_về { get; set; }
        public string Xăng_về { get; set; }
        public string Trạng_thái_về { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual XE XE { get; set; }
    }
}
