//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChoThueOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHCHOTHUE
    {
        public int STT { get; set; }
        public string Mã_KH { get; set; }
        public string Mã_loại { get; set; }
        public System.DateTime Ngày_đăng_ký { get; set; }
        public System.DateTime Ngày_thuê { get; set; }
        public int Số_ngày_thuê { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual LOAIXE LOAIXE { get; set; }
    }
}
