//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChoThueOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHTHUE
    {
        public string Số_xe { get; set; }
        public string Mã_KH { get; set; }
        public System.DateTime Ngày_giao { get; set; }
        public System.DateTime Ngày_trả { get; set; }
        public System.DateTime Ngày_giao_thực_tế { get; set; }
        public System.DateTime Gia_hạn { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual XE XE { get; set; }
    }
}
