//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChoThueOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUCO
    {
        public string Số_BBSC { get; set; }
        public string Số_xe { get; set; }
        public string Mã_KH { get; set; }
        public string Tên_SC { get; set; }
        public System.DateTime Ngày_BBSC { get; set; }
        public string Nội_dung_SC { get; set; }
        public string Tiền_phạt { get; set; }
        public string Mã_NV { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual XE XE { get; set; }
    }
}
