//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChoThueOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHTOAN
    {
        public string Số_HĐTT { get; set; }
        public string Số_HĐ { get; set; }
        public string Mã_NV { get; set; }
        public System.DateTime Ngày_thanh_toán { get; set; }
        public string Lý_do { get; set; }
        public string Hồ_sơ_kèm { get; set; }
        public string Tiền_TT { get; set; }
    
        public virtual HOPDONG HOPDONG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
