//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChoThueOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XE()
        {
            this.BIENBANGNs = new HashSet<BIENBANGN>();
            this.HOPDONGs = new HashSet<HOPDONG>();
            this.SUCOes = new HashSet<SUCO>();
        }
    
        public string Số_xe { get; set; }
        public string Mã_loại { get; set; }
        public string Tên_xe { get; set; }
        public string Phí_xăng { get; set; }
        public string Phí_quá_km { get; set; }
        public string Đơn_giá { get; set; }
        public string Mô_tả_tình_trạng { get; set; }
        public int Trạng_thái { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIENBANGN> BIENBANGNs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOPDONG> HOPDONGs { get; set; }
        public virtual LOAIXE LOAIXE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUCO> SUCOes { get; set; }
    }
}
